name: papermill
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - jupyter
  - xarray
  - netcdf4
  - matplotlib
  - papermill
  - pip
  - pip:
    - l2ss-py
    - harmony-py
    - cartopy
    - earthaccess
#prefix: /Users/gangl/miniconda3/envs/papermill
